version: "3"
services:
  elasticsearch:
    container_name: es-ubq
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./workdir/esdata:/usr/share/elsticsearch/data
    networks:
      - es-ubq-net
  kibana:
    container_name: kibana-ubq
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - 5601:5601
    networks:
      - es-ubq-net
networks:
  es-ubq-net:
